POST http://localhost:8080/empresa
Content-Type: application/json

{
  "cnpj": "27727094000151",
  "razaoSocial": "EMPRESA FICTÍCIA LTDA",
  "socios": [
    {
      "cpf": "51001960092",
      "nome": "FULANINHO DA SILVA"
    }
  ]
}

###
